DROP TABLE IF EXISTS rider_rides;
DROP TABLE IF EXISTS rides;

CREATE TABLE IF NOT EXISTS rides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id TEXT REFERENCES users(clerk_id) ON DELETE CASCADE,

    pickup_address TEXT,
    pickup_lat DOUBLE PRECISION,
    pickup_lng DOUBLE PRECISION,

    destination_address TEXT,
    destination_lat DOUBLE PRECISION,
    destination_lng DOUBLE PRECISION,

    seats INT CHECK (seats is null or seats > 0),

    started_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- rider_rides table to represent number of riders in a ride
CREATE TABLE IF NOT EXISTS rider_rides (
    ride_id BIGINT NOT NULL REFERENCES rides(id) ON DELETE CASCADE,
    rider_id TEXT NOT NULL REFERENCES users(clerk_id) ON DELETE CASCADE,
    PRIMARY KEY (ride_id, rider_id)
);

ALTER TABLE rides ENABLE ROW LEVEL SECURITY;
ALTER TABLE rider_rides ENABLE ROW LEVEL SECURITY;

-- All users
CREATE POLICY "Users can read rides" 
    ON public.rides FOR SELECT 
    USING (true);

CREATE POLICY "Users can read rider_rides"
    ON public.rider_rides FOR SELECT
    USING (true);

CREATE POLICY "Users can create a ride"
  ON public.rides FOR INSERT TO authenticated
  WITH CHECK (driver_id IS NULL OR driver_id = (select auth.jwt()->>'sub'));

-- Riders
CREATE POLICY "Rider can create rider_ride (join ride)"
  ON public.rider_rides FOR INSERT TO authenticated
  WITH CHECK (rider_id = (select auth.jwt()->>'sub'));

CREATE POLICY "Rider can delete rider_ride (leave ride)"
  ON public.rider_rides FOR DELETE TO authenticated
  USING (rider_id = (select auth.jwt()->>'sub'));

CREATE POLICY "Driver can delete rider_ride (remove rider from ride)"
  ON public.rider_rides FOR DELETE TO authenticated
  USING (ride_id IN (
    SELECT id FROM rides WHERE driver_id = (select auth.jwt()->>'sub')
  ));

-- Drivers
CREATE POLICY "Driver can join and update a ride"
  ON public.rides FOR UPDATE TO authenticated
  USING (driver_id = (select auth.jwt()->>'sub') OR driver_id IS NULL)
  WITH CHECK (driver_id = (select auth.jwt()->>'sub'));

CREATE POLICY "Driver can unclaim their ride if ride hasn't started"
  ON public.rides FOR UPDATE TO authenticated
  USING (driver_id = (select auth.jwt()->>'sub') AND started_at IS NULL)
  WITH CHECK (driver_id IS NULL);

-- Restrict column updates so drivers cannot change pickup/destination details after claiming
REVOKE UPDATE ON public.rides FROM authenticated;
GRANT UPDATE (driver_id, started_at, seats) ON public.rides TO authenticated;

